### ISSUE TITLE
insert recipe

### ISSUE THREAD

**Issue by KonstantinGasser** [KonstantinGasser/weeat#2]
Story: user want to be able to create a recipe with searched ingredients.

ToDo: 
- [x] web: allow to search for ingredients and add them to the recipe
- [x] web: transmit recipe with ingredients aka API call to backend
- [x] go: store recipe with set name
- [x] go: insert all ingredients in recipe_food_items table to map ingredients to a recipe and food

**Comment by KonstantinGasser** [comment]
finished in PR https://github.com/KonstantinGasser/weeat/commit/af325144d3b3f1ef5da174537194813123eece71
