### ISSUE TITLE
track daily intake

### ISSUE THREAD

**Issue by KonstantinGasser** [KonstantinGasser/weeat#3]
user story: as a user I want to be able to track my daily nutritions where the data will be delete completely after one day and the data is not mapped to any personal information of mine.

ToDos: 
- [ ] web: if accepted, set cookie as https-only cookie on client side
- [ ] go: generate token if requested must be set as https-only cookie
- [ ] go: map random uuid in cookie to intake data in database
